<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>2a3ba4f7-4b98-4615-94b2-76d61094ed23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-verify-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='recaptcha-verify-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>768f0d81-4bab-4851-a787-d94dc5a71379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-button-default goog-inline-block</value>
      <webElementGuid>0c1f65b5-1957-4b1d-bb07-121397802f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-verify-button</value>
      <webElementGuid>1d70da24-485e-49cc-9950-6c515f403c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b0d8ec5-8e7a-4dba-b897-4161e422f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>181d2f8f-e8c8-4628-a22b-76395a25e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-verify-button&quot;)</value>
      <webElementGuid>20fa2723-5a38-472f-b7ae-d39063ea3e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_c-j7msngw789h3</value>
      <webElementGuid>30e3c3c9-b13f-4756-a250-8ed8e23b47f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-verify-button']</value>
      <webElementGuid>cfda91bc-2351-4d5f-a6d6-a9e71999aaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[3]/div[2]/div/div[2]/button</value>
      <webElementGuid>b9b83008-0e1e-4b64-aefc-512526c26eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>350baef4-022a-41cb-87f2-77c6af708b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>5dbd7dda-5c87-4acb-83d7-41863caa9407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
