<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(katalon-rec_elementInfoDiv) (1)</name>
   <tag></tag>
   <elementGuidId>a8edeac2-e276-4e2c-8a7d-a81a1012cf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0df172a2-80b4-4fde-a5b0-aae553971f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
      <webElementGuid>0c138df7-f372-4524-8805-ece74a2863a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>10d63dd1-736b-4a1a-8225-7b05f17c4f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>40ee9093-0646-44a3-8be6-1ab2d9924366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_a-ad05bevflikt</value>
      <webElementGuid>e87d4a27-091f-436f-acf7-602b45185c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      <webElementGuid>c1403d00-e259-45cc-9e77-92e77640b146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
      <webElementGuid>7362a262-2db2-46d5-8b69-9f0d2dbf16f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>5e7160e5-8d6f-4521-a917-0edcb473ac48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;katalon-rec_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-rec_elementInfoDiv&quot;)')]</value>
      <webElementGuid>61202b59-3e1a-482e-9944-3231d21406b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
