<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-2naiy495x4i7</name>
   <tag></tag>
   <elementGuidId>6a2343fe-1eeb-48f9-b684-f330c0fd66d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-2naiy495x4i7&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-2naiy495x4i7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1366c0b9-09ab-4592-b44c-702818065d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>bc00fc69-d31d-41d2-b1bf-0294b6c6c03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>56f6c75e-27dc-42c6-aa15-2652a1352806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>5cb3ddcb-37af-4296-8886-a8359ac9091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b3e63bfc-af43-41d3-bd94-0c4a6de5e2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-2naiy495x4i7</value>
      <webElementGuid>3f317a98-39d1-4173-a202-58eabb791d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ca91db1-586d-4f2b-85af-3849c457693d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e700f823-8e29-41c0-b31f-d7a381222500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>5e6bbb76-e970-43d3-9c77-0a78b7a0a33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=MHBiAvbtvk5Wb2eTZHoP1dUd&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=lp86x15zm0bp</value>
      <webElementGuid>8cde9886-fea0-4cd6-871e-253dbccd0eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>efe640e8-1ae5-465e-a195-35f16118402b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-2naiy495x4i7']</value>
      <webElementGuid>95b7f10d-8806-446d-b462-f38fff641b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>29948f9a-d73b-471c-b8c1-221ad9755a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/iframe</value>
      <webElementGuid>cfca1fa8-6484-4aa8-898a-bf4a30ce6051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-2naiy495x4i7' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=MHBiAvbtvk5Wb2eTZHoP1dUd&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=lp86x15zm0bp']</value>
      <webElementGuid>b9a84566-b393-4123-959b-0e6d3ecc9021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
