<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>bb40ebd8-3de7-477f-9a85-01324945f6e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>07391dfe-11bf-4109-a55d-7df13ccdbeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>d76746a2-5f21-4688-8ca8-c7e9c46c43b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5SCwL2cew-uAGpDJbgiJkr-02HZBToH5QGv-6TaNcoNjy09u7Me_yxfNhGJE9qO1VI_suSfjJcMP3iXzPBffQZClrzfwyhGeE_fXEd9Eu2xnZ9zNd1G0mmbf0exImWzppaSnDQDojupJ9Sd4_8UCQ7fvRWCBJgmt65bZn7inqDesxLGpV8VjAqv1fM-6YhBvy06W-n&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>ac9aa95c-5500-44dc-853d-8277097d470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>f3a98704-c9ac-455d-b81f-dfda14060ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_c-j7msngw789h3</value>
      <webElementGuid>bcbbf2b2-7acd-4cb8-87a5-49adccaccc05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>40a71396-83c3-400e-853c-cdc401d6404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5SCwL2cew-uAGpDJbgiJkr-02HZBToH5QGv-6TaNcoNjy09u7Me_yxfNhGJE9qO1VI_suSfjJcMP3iXzPBffQZClrzfwyhGeE_fXEd9Eu2xnZ9zNd1G0mmbf0exImWzppaSnDQDojupJ9Sd4_8UCQ7fvRWCBJgmt65bZn7inqDesxLGpV8VjAqv1fM-6YhBvy06W-n&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')]</value>
      <webElementGuid>4aa37a03-02e9-4f6a-be38-3b71f8071078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cadf901d-3cfa-49e8-8f68-8772d7f7f100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5SCwL2cew-uAGpDJbgiJkr-02HZBToH5QGv-6TaNcoNjy09u7Me_yxfNhGJE9qO1VI_suSfjJcMP3iXzPBffQZClrzfwyhGeE_fXEd9Eu2xnZ9zNd1G0mmbf0exImWzppaSnDQDojupJ9Sd4_8UCQ7fvRWCBJgmt65bZn7inqDesxLGpV8VjAqv1fM-6YhBvy06W-n&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>48b8edd6-3f17-4964-950a-a10a9d01b551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
