<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33 (1)</name>
   <tag></tag>
   <elementGuidId>2120b3ae-91a7-4acb-b841-df5f94877f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>950f8bc0-e149-47e5-a37b-e7506f1515aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>325a29d6-0451-4731-bc1e-1d3349c0f80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4BgGfORg-ZUsnFb_KQZCl9PaTK3YeiJLHdlTMZ_M0mSYfU6UuazJH7WRVN5mICvZYVp40ZzYjNqIsHFwmU7actunofE0EVMYMnaF4_RGZr3MjsQw0pyjX4lqEITqibJnUp1LCcYSlpEstBuF2wIbDmdEm5NrdHktUZ4_MaUk9UP9SFSSC7MzNJmSVjxRRuIk4DBbvK&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>4210991e-b1af-454c-8795-4b6eace41709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>c9f2d7f9-e5fd-437c-9405-d126b3731b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_c-ad05bevflikt</value>
      <webElementGuid>476c76f4-9ec8-4f50-a145-1fcf7381f503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>9484f3b1-0b9d-4606-9bd8-0877be9243c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4BgGfORg-ZUsnFb_KQZCl9PaTK3YeiJLHdlTMZ_M0mSYfU6UuazJH7WRVN5mICvZYVp40ZzYjNqIsHFwmU7actunofE0EVMYMnaF4_RGZr3MjsQw0pyjX4lqEITqibJnUp1LCcYSlpEstBuF2wIbDmdEm5NrdHktUZ4_MaUk9UP9SFSSC7MzNJmSVjxRRuIk4DBbvK&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')]</value>
      <webElementGuid>59dbb5be-d328-4903-86c9-ac8a45beaf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bea61c90-7628-4062-bf18-cbfef165f11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4BgGfORg-ZUsnFb_KQZCl9PaTK3YeiJLHdlTMZ_M0mSYfU6UuazJH7WRVN5mICvZYVp40ZzYjNqIsHFwmU7actunofE0EVMYMnaF4_RGZr3MjsQw0pyjX4lqEITqibJnUp1LCcYSlpEstBuF2wIbDmdEm5NrdHktUZ4_MaUk9UP9SFSSC7MzNJmSVjxRRuIk4DBbvK&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>a419281d-ae97-40a3-9ecf-7b68d99a2439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
