<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputuserName</name>
   <tag></tag>
   <elementGuidId>7f179d66-f29a-4893-98a2-e953e567cb33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1f490ea-02a9-475f-923c-c77dad0dbe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>262ce612-d399-4e2e-9b1c-4bdc4f336a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>c9d2ddf8-9230-4902-9f1b-24f737717782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c25dc26-231a-4d65-b26f-d2ade874c287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>9f4b4990-8cc1-46ec-bd1c-0122d6f18110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-sm-2 form-control</value>
      <webElementGuid>0febadee-1139-4d32-8266-ab1924b3f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>88886137-72bd-438a-b6ad-c5f0c45629b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName&quot;)</value>
      <webElementGuid>84087e2b-c174-49d8-abdb-9c791c33d760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userName']</value>
      <webElementGuid>631d9f0f-a0af-4b3b-9912-9bfe4ae8c6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userName-wrapper']/div[2]/input</value>
      <webElementGuid>3478f943-4934-4e2e-9bff-c53bca89b1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>c4e43b32-1f4c-4521-bbbb-70b9e65eb37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'UserName' and @type = 'text' and @id = 'userName']</value>
      <webElementGuid>6d201758-4c2e-424f-9091-3085735d6c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
