<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputuserName (1)</name>
   <tag></tag>
   <elementGuidId>a9d40b60-0d39-419e-abed-d978ded0ca88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7de0d089-4563-494c-8dda-7fb1f09a62de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5dbb6bb-726c-4eee-9f81-c8cd055667b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>71d18579-9d80-41e0-8e3f-f4ea227cc78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afeb463a-7711-496d-a0d1-841f11a53b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>d3f7214d-9d91-446c-8c1b-fb5fecc17162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-sm-2 form-control</value>
      <webElementGuid>32d80fa3-0252-4c59-babb-2f3acc7165ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName&quot;)</value>
      <webElementGuid>8f7b473e-2deb-4cc3-b1d8-e5ecc1696119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userName']</value>
      <webElementGuid>32fb7bd2-a780-4f6d-944a-48aeb6353a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userName-wrapper']/div[2]/input</value>
      <webElementGuid>fc4a46e9-cffc-4947-9b78-41f0071b4c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>63a1427a-d193-4221-a2c0-e9c4bc7dfb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'UserName' and @type = 'text' and @id = 'userName']</value>
      <webElementGuid>3abb3f53-9c89-4679-b04b-f803a7baaa1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
