<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>25dfa1db-9d40-4d2d-af80-761e4fa2b2cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg > path:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>ce3b1531-d602-420c-a45c-9e2bfdfeeda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>824ec954-a0a5-4a5f-af94-7c9cee321d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M6.5 12a5.5 5.5 0 100-11 5.5 5.5 0 000 11zM13 6.5a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z</value>
      <webElementGuid>09181ea4-6b34-4fc7-a508-7d11bd977f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>ae429e7d-642a-472e-9910-43a30119a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-addon2&quot;)/span[1]/svg[1]/path[2]</value>
      <webElementGuid>87830c3c-6983-4049-b909-0abc9d184a9e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
